# 
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

GTEST_DIR = .
USER_DIR = $(GTEST_DIR)/src
LIB_DIR = $(GTEST_DIR)/lib
OBJ_DIR = $(GTEST_DIR)/.obj

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST_DIR)/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -lpthread

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = system_call_test

# All Google Test headers.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

all : $(TESTS)
	mkdir -p $(OBJ_DIR)
	mv *.o $(OBJ_DIR)

clean :
	rm -f $(TESTS) $(OBJ_DIR)/*

system_call_test.o : $(USER_DIR)/system_call_test.cc #$(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $^

system_call_test: system_call_test.o $(LIB_DIR)/gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@
